[en]
  title = "uRick"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
  title = "uRick"
  languageName = "中文简体"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"
