[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[main]]
identifier = "archives"
name = "Archives"
url = "archives"
weight = 2
[[main]]
identifier = "about"
name = "About"
url = "about"
weight = 3
[[main]]
identifier = "nav"
name = "Navigation"
url = "nav"
weight = 4
[[main]]
identifier = "more"
name = "More"
url = "more"
weight = 5
[[main]]
parent = "more"
identifier = "test1"
name = "test1"
url = "test1"
weight = 1
[[main]]
parent = "more"
identifier = "test2"
name = "test2"
url = "test2"
weight = 2
[[main]]
parent = "more"
identifier = "test3"
name = "test3"
url = "test3"
weight = 3